package ffviirse.domain.model.context

import ffviirse.domain.extension.asObservable
import ffviirse.domain.model.value.PartyMember.CLOUD_STRIFE
import ffviirse.domain.property.IntProperty
import ffviirse.domain.property.PartyMemberProperty
import javafx.beans.property.BooleanProperty
import javafx.beans.property.SimpleBooleanProperty
import javafx.collections.ObservableList

data class CharacterInfoContext(
    val characterMember: PartyMemberProperty = PartyMemberProperty(CLOUD_STRIFE),
    val characterLevel: IntProperty = IntProperty(0),
    val characterExperience: IntProperty = IntProperty(0),
    val characterRelationship: IntProperty = IntProperty(0),
    val characterHpcurrent: IntProperty = IntProperty(0),
    val characterHpmax: IntProperty = IntProperty(0),
    val characterMpcurrent: IntProperty = IntProperty(0),
    val characterMpmax: IntProperty = IntProperty(0),
    val characterAttack: IntProperty = IntProperty(0),
    val characterMattack: IntProperty = IntProperty(0),
    val characterDefense: IntProperty = IntProperty(0),
    val characterMdefense: IntProperty = IntProperty(0),
    val characterStrength: IntProperty = IntProperty(0),
    val characterMagic: IntProperty = IntProperty(0),
    val characterVitality: IntProperty = IntProperty(0),
    val characterSpirit: IntProperty = IntProperty(0),
    val characterLuck: IntProperty = IntProperty(0),
    val characterSpeed: IntProperty = IntProperty(0),
    val criticalHrate: IntProperty = IntProperty(0),
    val characterWeapon: IntProperty = IntProperty(0),
    val characterArmor: IntProperty = IntProperty(0),
    val characterSummon: IntProperty = IntProperty(0),
    val characterAccessory: IntProperty = IntProperty(0),
    val statBoost01: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost02: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost03: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost04: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost05: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost06: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost07: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost08: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost09: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost10: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost11: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost12: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost13: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost14: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost15: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost16: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost17: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost18: BooleanProperty = SimpleBooleanProperty(false),
    val statBoost19: BooleanProperty = SimpleBooleanProperty(false),
    val limitBreak: BooleanProperty = SimpleBooleanProperty(false),
    val characterAbility01: BooleanProperty = SimpleBooleanProperty(false),
    val characterAbility02: BooleanProperty = SimpleBooleanProperty(false),
    val characterAbility03: BooleanProperty = SimpleBooleanProperty(false),
    val characterAbility04: BooleanProperty = SimpleBooleanProperty(false),
    val characterAbility05: BooleanProperty = SimpleBooleanProperty(false),
    val synergySkill01: BooleanProperty = SimpleBooleanProperty(false),
    val synergySkill02: BooleanProperty = SimpleBooleanProperty(false),
    val synergySkill03: BooleanProperty = SimpleBooleanProperty(false),
    val synergyAbility01: BooleanProperty = SimpleBooleanProperty(false),
    val synergyAbility02: BooleanProperty = SimpleBooleanProperty(false),
    val synergyAbility03: BooleanProperty = SimpleBooleanProperty(false),
    val synergyAbility04: BooleanProperty = SimpleBooleanProperty(false),
    val synergyAbility05: BooleanProperty = SimpleBooleanProperty(false),
    val synergyAbility06: BooleanProperty = SimpleBooleanProperty(false),
    val weaponMaterias: ObservableList<Int> = listOf<Int>().asObservable(),
    val armorMaterias: ObservableList<Int> = listOf<Int>().asObservable(),
)
