package ffviirse.domain.model.entity

import ffviirse.domain.model.value.PartyMember

data class CharacterInfo(
    val characterMember: PartyMember = PartyMember.CLOUD_STRIFE,
    val characterLevel: Int = 0,
    val characterExperience: Int = 0,
    val characterRelationship: Int = 0,
    val characterHpcurrent: Int = 0,
    val characterHpmax: Int = 0,
    val characterMpcurrent: Int = 0,
    val characterMpmax: Int = 0,
    val characterAttack: Int = 0,
    val characterMattack: Int = 0,
    val characterDefense: Int = 0,
    val characterMdefense: Int = 0,
    val characterStrength: Int = 0,
    val characterMagic: Int = 0,
    val characterVitality: Int = 0,
    val characterSpirit: Int = 0,
    val characterLuck: Int = 0,
    val characterSpeed: Int = 0,
    val criticalHrate: Int = 0,
    val characterWeapon: Int = 0,
    val characterArmor: Int = 0,
    val characterSummon: Int = 0,
    val characterAccessory: Int = 0,
    val statBoost01: Boolean = false,
    val statBoost02: Boolean = false,
    val statBoost03: Boolean = false,
    val statBoost04: Boolean = false,
    val statBoost05: Boolean = false,
    val statBoost06: Boolean = false,
    val statBoost07: Boolean = false,
    val statBoost08: Boolean = false,
    val statBoost09: Boolean = false,
    val statBoost10: Boolean = false,
    val statBoost11: Boolean = false,
    val statBoost12: Boolean = false,
    val statBoost13: Boolean = false,
    val statBoost14: Boolean = false,
    val statBoost15: Boolean = false,
    val statBoost16: Boolean = false,
    val statBoost17: Boolean = false,
    val statBoost18: Boolean = false,
    val statBoost19: Boolean = false,
    val limitBreak: Boolean = false,
    val characterAbility01: Boolean = false,
    val characterAbility02: Boolean = false,
    val characterAbility03: Boolean = false,
    val characterAbility04: Boolean = false,
    val characterAbility05: Boolean = false,
    val synergySkill01: Boolean = false,
    val synergySkill02: Boolean = false,
    val synergySkill03: Boolean = false,
    val synergyAbility01: Boolean = false,
    val synergyAbility02: Boolean = false,
    val synergyAbility03: Boolean = false,
    val synergyAbility04: Boolean = false,
    val synergyAbility05: Boolean = false,
    val synergyAbility06: Boolean = false,
    val weaponMaterias: List<Int> = listOf(),
    val armorMaterias: List<Int> = listOf(),
)
